Data Visualization/Project/morality/main/urls.py
from django.conf.urls import url
from main.views import index

app_name='main'
urlpatterns = [
    url(r'^', index, name='index')
]

Data Visualization/Project/morality/morality/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^geodata/', include('geodata.urls')),
    url(r'^survey/', include('surveys.urls')),
    url(r'^$', include('main.urls')),
]

Data Visualization/Project/morality/surveys/urls.py
from django.conf.urls import url
from surveys.views import survey

app_name = 'surveys'
urlpatterns = [
    url(r'^', survey, name='survey'),
]

Data Visualization/Project/morality/surveys/models.py
from __future__ import unicode_literals

from django.db import models

class Survey(models.Model):
	STATES = [('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')]
	Q1  = (('-1','Refused')
                ,('1', 'Strongly disagree')
                ,('2', 'Disagree')
                ,('3', 'Somewhat disagree') 
		,('4', 'Neither agree nor disagree')
                ,('5', 'Somewhat agree')
                ,('6', 'Agree')
                ,('7', 'Strongly agree'))
	Q3 = (('-1', 'Refused')
                ,('1', 'Strongly agree')
                ,('2', 'Agree')
                ,('3', 'Somewhat agree')
                ,('4', 'Neither agree nor disagree')
                ,('5', 'Somewhat disagree')
                ,('6', 'Disagree')
                ,('7', 'Strongly disagree'))
	state = models.CharField(max_length=2, choices=STATES)
	gender = models.CharField(max_length=5, choices=(('Male','Male'),('Female','Female')))
	i_develop_strong_emotions_toward_people_i_can_rely_on = models.CharField(max_length=1, choices=Q1)
	parents_should_empower_children_as_much_as_possible_so_that_they_may_follow_their_dreams = models.CharField(max_length=1, choices=Q1)
	moral_standards_should_be_seen_as_individualistic_what_one_person_considers_to_be_moral_may_be_judged_as_immoral_by_another_person = models.CharField(max_length=1, choices=Q3)
	video_choice = models.CharField(max_length=10, blank=True, null=True)

Data Visualization/Project/morality/surveys/forms.py
from django.forms import ModelForm
from surveys.models import Survey

class SurveyForm(ModelForm):
	class Meta:
		model = Survey
		fields = '__all__'

Data Visualization/Project/morality/surveys/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import loader

from .models import Survey
from .forms import SurveyForm

def survey(request):
	if request.method == 'POST':
		video = request.session.get('video')
		postdata = request.POST.copy()
		postdata['video_choice'] = video
		f = SurveyForm(postdata)
		if f.is_valid():
			f.save()
			request.session['watched_video'] = True
			return HttpResponseRedirect('/')
	else:
		f = SurveyForm()
	tmp = loader.get_template('survey_form.html')
	return HttpResponse(tmp.render({'form':f}, request))

Data Visualization/Project/morality/templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load staticfiles %}

<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">



<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">


 <!--[if lt IE 9]>
 <script src="{% static "js/html5shiv.js" %}"></script>
 <script src="{% static "js/respond.min.js" %}"></script>
 <![endif]-->   

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
<script src="{% static "js/datamaps.usa.min.js" %}"></script>

</head>
<body>

<div class="container-fluid">
	{% block main %}{% endblock %}
</div>

</body>
<script>
{% include "map_script.html" %}
</script>
</html>

Data Visualization/Project/morality/templates/index.html
{% extends "base.html" %}

{% block main %}

<div class="row">
<div class="col-xs-12 col-md-offset-2 col-md-8">

{% include "index_headline.html" %}
{% include "index_headline_subtext.html" %}

</div> <!-- col -->
</div> <!-- row -->


<div class="row">
<div class="col-xs-12 col-md-offset-2 col-md-8">

<h1 id=nav class=page-header>Contribute</h1>

{% include "index_video.html" %}

</div> <!-- col -->
</div> <!-- row -->

<div class="row">
<div class="col-xs-12 col-md-offset-2 col-md-8">
<h1 id=nav class=page-header>Responses</h1>

{% include "index_mapcharts.html" %}

</div> <!-- col -->
</div> <!-- row -->

<div class="row">
<div class="col-xs-12 col-md-offset-2 col-md-8">

<h1 id=nav class=page-header>Analysis</h1>

{% include "index_analysis.html" %}

</div> <!-- col -->
</div> <!-- row -->

{% endblock %}

Data Visualization/Project/morality/templates/index_analysis.html
<p class="lead">
Live analysis of morality across the US. 
</p>
<p>
This analysis will refresh with responses as they flow into the site. 
</p>

Data Visualization/Project/morality/templates/index_headline.html
  
<div class="page-header">
<h1>Morality <small>across America</small></h1>
</div>

Data Visualization/Project/morality/templates/index_headline_subtext.html
 <p class='lead'>
Data visualization of morality in America.
</p>
 <p>We've worked hard to create the visualizations below, based on data from the Duke
        morality survey conducted in YYYY, plus LIVE data from participants like you!
  </p>
  <p>Feel free to participate below, or scroll down to review our visualizations and
        learn about people's thoughts on morality.</p>

Data Visualization/Project/morality/templates/index_mapcharts.html
<p>
Below are results from the Duke morality survey, plus additional data 
as filled out by our site viewers. They indicate that morality does differ
somewhat by region.
</p>
<br/>

<div class="row">
<div class="col-xs-12 col-md-offset-1 col-md-10">
<div class="panel panel-default">
  <div class="panel-heading">	
	<h3 class="panel-title">I develop strong emotions toward people I can rely on</h3>
  </div>
  <div class="panel-body">
<div id="resultmap_q1" style="position: relative; width: 750px; height: 500px;"></div>
</div>
</div>
</div> <!-- col -->
</div> <!-- row -->

<div class="row">
<div class="col-xs-12 col-md-offset-1 col-md-10">
<div class="panel panel-default">
  <div class="panel-heading">	
    <h3 class="panel-title">Parents should empower children as much as possible so that they may follow their dreams</h3>
  </div>
  <div class="panel-body">
<div id="resultmap_q2" style="position: relative; width: 750px; height: 500px;"></div>
</div>
</div>
</div> <!-- col -->
</div> <!-- row -->

<div class="row">
<div class="col-xs-12 col-md-offset-1 col-md-10">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Moral standards should be seen as individualistic what one person considers to be moral may be judged as immoral by another person</h3>
  </div>
  <div class="panel-body">
<div id="resultmap_q3" style="position: relative; width: 750px; height: 500px;"></div>
</div>
</div>
</div> <!-- col -->
</div> <!-- row -->

Data Visualization/Project/morality/templates/index_video.html
<p class="lead">
Participate in our research. 
</p>
<p>
To participate in our morality research, watch 
the below video and answer our survey questions. 
</p>

<p>Watch the video below, and then click 'Go to survey'
to fill out a short 5-minute questionnaire about morality.
Your responses will automatically be added to the visualizations
on this page.</p>
<p>We appreciate your participation!</p>

<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" src="{{ video }}" allowfullscreen></iframe>
</div>

{% if watched_video %}

<br/>
<div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
  </button>
  <strong>Thanks!</strong> Your response was recorded.
</div>

{% else %}

<br/>
<a href="{% url 'surveys:survey' %}" class='btn btn-primary'>Go to survey</a>

{% endif %}

Data Visualization/Project/morality/templates/map_script.html
function zeroifnull(x) {
	if (typeof x == 'undefined') {
		return 0	
	} else {
		return x
	}
}

var resultmap_q1 = new Datamap({
  scope: 'usa',
  element: document.getElementById('resultmap_q1'),
  geographyConfig: {
    highlightBorderColor: '#bada55',
	popupTemplate: function(geography, data) {
      	return '<div class="hoverinfo"><strong>' + geography.properties.name + '</strong>' +
          '<br />Strongly Agree: ' + zeroifnull(data.stronglyAgree) + 
          '<br />Agree: ' + zeroifnull(data.agree) + 
          '<br />Somewhat agree: ' + zeroifnull(data.somewhatAgree) +
          '<br />Neither agree nor disagree: ' + zeroifnull(data.neitherAgreeNorDisagree) +
          '<br />Somewhat disagree: ' + zeroifnull(data.somewhatDisagree) +
          '<br />Disagree: ' + zeroifnull(data.disagree) +
          '<br />Strongly disagree: ' + zeroifnull(data.stronglyDisagree) +
          '<br />Refused: ' + zeroifnull(data.refused) + ' </div>'
    },
    highlightBorderWidth: 3
  },

  fills: {
    {{ fillkey|safe }}
},data:{{ map1data|safe }} 
});
resultmap_q1.labels();


var resultmap_q2 = new Datamap({
  scope: 'usa',
  element: document.getElementById('resultmap_q2'),
  geographyConfig: {
    highlightBorderColor: '#bada55',
    popupTemplate: function(geography, data) {
	return '<div class="hoverinfo"><strong>' + geography.properties.name + '</strong>' +
          '<br />Strongly Agree: ' + zeroifnull(data.stronglyAgree) +
          '<br />Agree: ' + zeroifnull(data.agree) +
          '<br />Somewhat agree: ' + zeroifnull(data.somewhatAgree) +
          '<br />Neither agree nor disagree: ' + zeroifnull(data.neitherAgreeNorDisagree) +
          '<br />Somewhat disagree: ' + zeroifnull(data.somewhatDisagree) +
          '<br />Disagree: ' + zeroifnull(data.disagree) +
          '<br />Strongly disagree: ' + zeroifnull(data.stronglyDisagree) +
          '<br />Refused: ' + zeroifnull(data.refused) + ' </div>'
          },
    highlightBorderWidth: 3
  },
  fills: {
	{{ fillkey|safe }}
    },data: {{ map2data|safe }}
});
resultmap_q2.labels();


var resultmap_q3 = new Datamap({
  scope: 'usa',
  element: document.getElementById('resultmap_q3'),
  geographyConfig: {
    highlightBorderColor: '#bada55',
    popupTemplate: function(geography, data) {
	return '<div class="hoverinfo"><strong>' + geography.properties.name + '</strong>' +
          '<br />Strongly Agree: ' + zeroifnull(data.stronglyAgree) +
          '<br />Agree: ' + zeroifnull(data.agree) +
          '<br />Somewhat agree: ' + zeroifnull(data.somewhatAgree) +
          '<br />Neither agree nor disagree: ' + zeroifnull(data.neitherAgreeNorDisagree) +
          '<br />Somewhat disagree: ' + zeroifnull(data.somewhatDisagree) +
          '<br />Disagree: ' + zeroifnull(data.disagree) +
          '<br />Strongly disagree: ' + zeroifnull(data.stronglyDisagree) +
          '<br />Refused: ' + zeroifnull(data.refused) + ' </div>'
          },
    highlightBorderWidth: 3
  },

   fills: {
	{{ fillkey|safe }}
    }, data:{{ map3data|safe }}
});
resultmap_q3.labels();

Data Visualization/Project/morality/templates/survey_form.html
{% extends "base.html" %}

{% block main %}

<div class="row">
<div class="col-xs-12 col-md-offset-2 col-md-8">

{% include "index_headline.html" %}

</div> <!-- col -->
</div> <!-- row -->


<div class="row">
<div class="col-xs-12 col-md-offset-2 col-md-8">

<p class="lead">
Please fill out our survey to add your perspective.
</p>

<form action="/survey/" method="post">
    {% csrf_token %}
	
	{{ form.non_field_errors }}
	<div class="form-group">
		<label for="{{ form.state.id_for_label }}">State: </label>
		{{ form.state }}
		{{ form.state.errors }}
	</div>
	
	{{ form.non_field_errors }}
	<div class="form-group">
		<label for="{{ form.gender.id_for_label }}">Gender: </label>
		{{ form.gender }}
		{{ form.gender.errors }}
	</div>
  	
	{{ form.non_field_errors }}
	<div class="form-group">
		<label for="{{ form.i_develop_strong_emotions_toward_people_i_can_rely_on.id_for_label }}">I develop strong emotions toward people I can rely on: </label>
		{{ form.i_develop_strong_emotions_toward_people_i_can_rely_on }}
		{{ form.i_develop_strong_emotions_toward_people_i_can_rely_on.errors }}
	</div>
	 
	{{ form.non_field_errors }}
	<div class="form-group">
		<label for="{{ form.parents_should_empower_children_as_much_as_possible_so_that_they_may_follow_their_dreams.id_for_label }}">Parents should empower children as much as possible so that they may follow their dreams: </label>
		{{ form.parents_should_empower_children_as_much_as_possible_so_that_they_may_follow_their_dreams }}
		{{ form.parents_should_empower_children_as_much_as_possible_so_that_they_may_follow_their_dreams.errors }}
	</div>
	
	{{ form.non_field_errors }}
	<div class="form-group">
		<label for="{{ form.moral_standards_should_be_seen_as_individualistic_what_one_person_considers_to_be_moral_may_be_judged_as_immoral_by_another_person.id_for_label }}">Moral standards should be seen as individualistic - <br/>What one person considers to be moral may be judged as immoral by another person: </label>
		{{ form.moral_standards_should_be_seen_as_individualistic_what_one_person_considers_to_be_moral_may_be_judged_as_immoral_by_another_person }}
		{{ form.moral_standards_should_be_seen_as_individualistic_what_one_person_considers_to_be_moral_may_be_judged_as_immoral_by_another_person.errors }}
	</div>
	
    <input class="btn btn-primary" type="submit" value="Submit" />
    <a href="{% url 'main:index' %}" class='btn btn-default'>Back</a>
</form>

</div> <!-- row -->
</div> <!-- col -->

{% endblock %}

Data Visualization/Project/morality/templates/video.html
{% extends "index.html" %}

{% block test_video %}

<div class="row">
<div class="col-xs-12 col-md-offset-2 col-md-8">

<p class="lead">
To participate in our morality research, watch 
the below video and answer our survey questions. 
</p>

<p>When you return from the survey, your data will  
automatically fill our visualizations below.</p>
{{ video|safe }}
{% if watched_video %}

<br/>
<div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
  </button>
  <strong>Thanks!</strong> Your response was recorded.
</div>

{% else %}

<br/>
<a href="{% url 'surveys:survey' %}" class='btn btn-primary'>Go to survey</a>

{% endif %}
</div> <!-- col -->
</div> <!-- row -->

{% endblock %}